---
collections:
  - name: https://github.com/ansible-collections/community.general
    type: git
  - name: https://github.com/ansible-collections/community.windows
    type: git
  - name: https://github.com/ansible-collections/amazon.aws.git
    type: git
  - name: https://github.com/ansible-collections/kubernetes.core
    type: git

 
