---
collections:
  - name: community.general
    version: 4.8.3
  - name: community.windows
    version: 1.10.0
  - name: community.aws
    version: 2.3.0
  - name: kubernetes.core
    version: 2.4.0
  - name: amazon.aws
    version: 2.3.0    