---
collections:
  - name: community.general
    version: ">=7.4.0"   
  - name: community.windows
    version: ">=2.0.0"
  - name: community.aws
    version: ">=6.3.0"
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: community.vmware
    version: ">=4.1.0"
  - name: community.general  