---
collections:
  - name: community.general
    version: ">=9.5.2"   
  - name: community.windows
    version: ">=2.3.0"
  - name: community.aws
    version: ">=9.0.0"
  - name: kubernetes.core
    version: ">=3.2.0"

 
