- name: Get PPDM Configuration
  uri:
    method: PUT
    url: "{{ ppdm_baseurl }}:{{ ppdm_port }}{{ ppdm_api_ver }}/server-disaster-recovery-configurations/{{ body.id }}"
    body_format: json 
    headers:
      accept: application/json
      authorization: "Bearer {{ access_token }}"
    body: "{{ body }}"      
    status_code: 200,500
    validate_certs: false
  register: result  
  when: not ansible_check_mode 
- set_fact:
    query_server_disaster_recovery_configuration: "{{ result.json }}"
