# Example Playbok Disabple Strict API Enforcement
- name: Configure PPDM
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
    - ./vars/main.yml
  vars: 
    state: "false"  
  tasks:
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdm fqdn set !"
    when: (ppdm_fqdn is not defined) or (ppdm_fqdn|length <= 8)
  - name: Checking Required Variables
    fail: 
      msg: "We do not have ppdm_new_password  set !"
    when: (ppdm_new_password is not defined) or (ppdm_new_password|length == 0)    
  - name: Setting Base URL
    set_fact: 
      ppdm_baseurl: "https://{{ ppdm_fqdn | regex_replace('^https://') }}"  
  - name: Get PPDM Token for https://{{ ppdm_fqdn | regex_replace('^https://') }}
    include_role: 
      name: get_ppdm_token
    vars: 
      ppdm_password: "{{ ppdm_new_password }}"
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
    name: our do we have a token ?  
  - name: Get PPDM Configuration 
    include_role: 
      name: set_ppdm_common_settings
    vars: 
      data: 
        id: REST_API_SETTING
        properties:
          - name: enableStrictValidation
            value: "{{ state }}"
            type: BOOLEAN
  - debug:
      msg: "{{ common_setting }}"
      verbosity: 0


     