# Example Playbok to deploy agents
- name: Ensure AgentSerive Running
  hosts: windows
  vars:
   agent_src: /tmp
  vars_files: 
    - ./vars/main.yml
    - ./vars/agents_vars.yaml
  tasks:
  - name: Set service startup mode to auto and ensure it is started 
    ansible.windows.win_service:
      name: AgentService
      state: started
      start_mode: delayed   

