# Example Playbok to deploy agentzs
- name: Get Agent Status
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
    - ./vars/main.yml
    - ./vars/agents_vars.yaml
  vars:
   agent_ver: "1915"
   agent_branch: "19.15-69"  
  tasks:
  - name: Checking Required Variable ppdm_fqdn
    fail: 
      msg: "We do not have ppdm fqdn set !"
    when: (ppdm_fqdn is not defined) or (ppdm_fqdn|length <= 8)
  - name: Checking Required Variable ppdm_new_password
    fail: 
      msg: "We do not have ppdm_new_password  set !"
    when: (ppdm_new_password is not defined) or (ppdm_new_password|length == 0)  
 
  - name: Setting Base URL
    set_fact: 
      ppdm_baseurl: "https://{{ ppdm_fqdn | regex_replace('^https://') }}"   
  - name: Get PPDM Token for https://{{ ppdm_fqdn | regex_replace('^https://') }}
    include_role: 
      name: get_ppdm_token
    vars: 
      ppdm_password: "{{ ppdm_new_password }}"
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
    name: do we have a token ?  

  - name: get agent registration status
    include_role:
      name: get_ppdm_agent_registration_status
    vars:
      filter: "{{ myfilter | default('') }}"  

  - name: Assets Result
    debug: 
      msg: "{{ agent_registration_status }}"
      verbosity: 0   
    when: agent_registration_status is defined



  - name: Extract agent IDs and application types
    set_fact:
      extracted_agents: []

  - name: Build list of agent IDs and application types
    set_fact:
      extracted_agents: "{{ extracted_agents + [ { 'id': item.hostId, 'privileged': item.agent.userDetail.privileged,'appServerTypes': item.applications | map(attribute='type') | list } ] }}"
    loop: "{{ agent_registration_status }}"


  - name: Assets Result Extract
    debug: 
      msg: "{{ extracted_agents }}"
      verbosity: 0   
    when: extracted_agents is defined

  - name: Update Agents from extracted List
    include_role:
      name: set_ppdm_agent_update_sessions
    vars:
      update_hosts: "{{ extracted_agents }}"
      precheckOnly: "{{ precheckOnly | bool }}"
    when:
     - extracted_agents is defined    


  - name: Set Update Result
    debug: 
      msg: "{{ agent_update }}"
      verbosity: 0   
    when: agent_update is defined

  - name: get agents update status
    include_role:
      name: get_ppdm_agents_update_sessions
    vars:
      id: "{{ agent_update.id }}"  


  - name: update sessions results
    debug: 
      msg: "{{ agents_update_sessions }}"
      verbosity: 0   
    when: agents_update_sessions is defined

