# Example Playbook to configure query PPDM Server Disaster Recovery
- name: Get sync-instance
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
    - ./vars/main.yml
  tasks:
  - name: Setting Base URL
    set_fact: 
      ppdm_baseurl: "https://{{ ppdm_fqdn | regex_replace('^https://') }}"     
  - name: Get PPDM Token for https://{{ ppdm_fqdn | regex_replace('^https://') }}
    include_role: 
      name: get_ppdm_token
    vars: 
      ppdm_password: "{{ ppdm_new_password }}"
  - debug: 
      msg: "{{ access_token }}"
      verbosity: 1
    name: do we have a token ?  
  - name: Grun sync-instance
    include_role: 
      name: run_ppdm_sync-instance
    vars:
      srcSystemId: "c6360aec-36df-40d2-ac08-f0b0a932d43e" 
      dstSystemId: "eda77468-23e7-4df5-8394-aee8b4e7b278"
