# Example Playbook to Install PPDM Update
#
# Note: Api is still called Upgrade, but Upgrade is for Hardware only !
# SO tasks will be named update but execute Upgrade
#
- name: Prepare S3
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files: 
    - ./vars/main.yml
  vars:
    s3_bucket: dps-products
    s3_host: http://ansible.demo.local:9000
    access_key: minioadmin
    secret_key: Password123!
    s3_container: powerprotect
    release: 19.16
  tasks:
  - name: Setting S3Bucket
    amazon.aws.s3_bucket:
      state: present
      name: "{{ s3_bucket}}"
      endpoint_url: "{{ s3_host }}"
      versioning: false
      access_key: "{{ access_key }}"
      secret_key: "{{ secret_key }}"

  - name: "create {{ s3_container }}}"
    amazon.aws.aws_s3:
      bucket: "{{ s3_bucket}}"
      object: "{{ s3_container }}/{{ release }}"
      mode: create
      encrypt: false
      endpoint_url: "{{ s3_host }}"
      access_key: "{{ access_key }}"      
      secret_key: "{{ secret_key }}"