- name: Get PPDM FLR Agents List
  uri:
    method: GET
    url: "{{ ppdm_baseurl }}:{{ ppdm_port }}/ppdm/vm-flr-agents"
    body_format: json
    return_content: true
    follow_redirects: true
    headers:
      connection_encoding: br
      content_type: application/json
      accept: "application/json, text/plain, */*"
      # authorization: "Bearer {{ access_token }}" 
      Cookie: "_csfr={{ login.cookies_string }}"
    status_code: 200,500
    validate_certs: false
  register: result  
- set_fact:
    flr_agents_list: "{{ result.content }}"
- debug:
    msg: "{{ flr_agents_list }}"
    verbosity: 0    

